export const ADD_TO_CART = "ADD_TO_CART"
export const DELETE_FROM_CART = "DELETE_FROM_CART"

export const CART_PRODUCT_INCREMENT = "CART_PRODUCT_INCREMENT"
export const CART_PRODUCT_DECREMENT = "CART_PRODUCT_DECREMENT"